CERT-Polska/malduck

- requirements.txt
Current version (master) uses only PyCryptodome
> 'cryptography' is no longer used by malduck

- docs/crypto.rst
- malduck/bits.py
- malduck/compression/gzip.py
- malduck/compression/lznt1.py
- malduck/crypto/aes.py
- malduck/crypto/blowfish.py
- malduck/crypto/des3.py
- malduck/crypto/rabbit.py
- malduck/crypto/rc.py
- malduck/crypto/serpent.py
- malduck/crypto/xor.py
- Fixed `malduck.compression` docs a bit
- Added more verbose documentation of `malduck.crypto` algorithms, including only supported forms.
Documentation can be generated by:
```
$ pip install -e .
$ pip install -r docs/requirements.txt
$ cd docs
$ make html
```
HTML files will be contained in `docs/_build/html`.
> [docs] Documentation of crypto module

- docs/string.rst
- malduck/crypto/rsa.py
- malduck/string/bin.py
- tests/test_string.py
- Legacy `malduck.bigint` switches between `int` and `bytes` representation which is counter-intuitive and makes scripts more difficult to read
- Deprecated `malduck.bigint` in favor of `malduck.bigint.unpack` and `malduck.bigint.pack` methods
- Added big-endian variants `malduck.bigint.unpack_be` and `malduck.bigint.pack_be`.
- `bitsize` argument is not used in newer variants (is looks to be relevant only for packing, maybe we should implement it only for `pack` methods)
- Added typings and tests
Closes #10
> Add bigint.unpack and bigint.pack methods

- .github/workflows/lint-test.yml
3.6.0 version is pretty outdated and doesn't know how to deal with `if TYPE_CHECKING` used to avoid cyclic references.
> CI: Bumped flake8 to 3.8.3

- malduck/__init__.py
- malduck/extractor/extract_manager.py
- malduck/extractor/extractor.py
- malduck/extractor/extractor.pyi
- malduck/procmem/procmem.pyi
- malduck/yara.py
- tests/files/modules/olly/olly.py
- tests/files/modules/weak/weak.py
- tests/test_extractor.py
- Simplified `Extractor` classes. Removed `MetaExtractor` metaclass and `ExtractorBase` base class
- Added rule-based methods (`@Extractor.rule`, closes #6)
- Much better typings for extractor method decorators:
- You can't mix `@final`, `@rule` and `@extractor` decorators
- Strict signature check-up of decorated methods
- `@needs_pe` allows to set `p: ProcessMemoryPE` typing and forbids `p: ProcessMemoryELF`
- `@weak`, `@needs_*` decorators can be used only on methods already decorated by `@final`/`@rule`/`@extractor`
- Fixed documentation
> Typed extractor methods and `@Extractor.rule` decorator support

- malduck/__init__.py
- malduck/extractor/extract_manager.py
- malduck/extractor/extractor.py
- malduck/extractor/extractor.pyi
- malduck/procmem/procmem.py
- malduck/procmem/procmem.pyi
- malduck/yara.py
- malduck/yara.pyi
- tests/files/modules/multirules/__init__.py
- tests/files/modules/multirules/multirule.py
- tests/files/modules/multirules/multirules.yar
- tests/files/modules/multirules/multistring.py
- tests/files/yara/digit_group.yar
- tests/test_extractor.py
- tests/test_yara.py
- Extended version of `@Extractor.extractor` methods called `@Extractor.string`
```python
class Evil(Extractor):
yara_rules = ("evil", "weird")
family = "evil"
...
@Extractor.string("accepts", "multiple", "strings")
def hello_evil(self, p: ProcessMemory, addr: int, match: YaraStringMatch):
if match.identifier == "accepts":
return {"hello_message": match.content}
```
- `malduck.yara` extended structures: `YaraRulesetMatch`, `YaraRuleMatch`, `YaraStringMatch`
- structures offering legacy offset-only interface: `YaraRulesetOffsets` (`YaraMatches`), `YaraRuleOffsets` (`YaraMatch`)
- both extended and legacy versions are available via `ProcessMemory.yarap/v` and `Yara.match` methods. We can choose new structures via additional `extended=True` argument, which is set to False by default.
Other …
> Extended Yara match structures, @Extractor.string with additional `match` argument

- malduck/extractor/extractor.py
This was introduced when changing the match type from `int` to `YaraStringMatch`
```
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
msg = self.format(record)
File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
return fmt.format(record)
File "/usr/lib/python3.7/logging/__init__.py", line 608, in format
record.message = record.getMessage()
File "/usr/lib/python3.7/logging/__init__.py", line 369, in getMessage
msg = msg % self.args
TypeError: %x format: an integer is required, not YaraStringMatch
Call stack:
File "/home/michal/work/malduck/venv/bin/malduck", line 33, in <module>
sys.exit(load_entry_point('malduck', 'console_scripts', 'malduck')())
File …
```
> Fix function formatter print

- .github/workflows/release.yml
Python 2 support is dropped, it's unnecessary to generate universal wheel package.
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#pure-python-wheels
> CI: Don't generate universal wheel

- malduck/procmem/procmem.py
- malduck/procmem/procmempe.py
In addition to https://github.com/CERT-Polska/malduck/pull/37
There are plenty of methods of ProcessMemory object initialization:
- `mmap` passed via constructor (not owned by constructed object and should be closed by mmap creator)
- `procmem.from_file` - opens file and creates mmap object, both things should be closed by `close()` method
- `procmem.from_memory` derives mmap object from original procmem, mmap is still owned by original object.
`self.opened_file` indicates that mapped file was opened by `from_file` method.
> Fix premature file/mmap closing

- malduck/procmem/procmem.py
In the fixed example, `procmempe.from_memory(p)` was used without that `procmempe` was imported
> Add missing procmempe in docs

- malduck/procmem/__init__.py
- malduck/procmem/idamem.py
- malduck/procmem/procmem.py
- malduck/procmem/procmem.pyi
During the large code migration in #16 an unintended regression was introduced that dropped support for custom memory objects in procmem's constructor: https://github.com/CERT-Polska/malduck/commit/4bbf43add1ea20e278e2fe8cec5577a5e0869803#diff-767505ff127f0f90757a6e16449a659bR84
As a result, starting from 4.0.0, attempts to initiate `idamem` object in IDAPython fail: 
```python
Python>from malduck import idamem
Python>idamem()
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.6/dist-packages/malduck/procmem/idamem.py", line 67, in __init__
super().__init__(IDAVM(self), regions=regions)
File "/usr/local/lib/python3.6/dist-packages/malduck/procmem/procmem.py", line 92, in __init__
"Wrong buffer type - must be bytes, bytearray or mmap …
```
> Fix idamem usage, add MemoryBuffer metaclass

- malduck/procmem/idamem.py
In the procmem [docs](https://malduck.readthedocs.io/en/latest/procmem.html?highlight=wide#malduck.procmem.idamem.IDAProcessMemory) there is a usage of `asciiz` instead of `utf16z`
```
some_wide_string = ida.asciiz(0x402010).decode("utf-16")
```
> Use utf16z in the docs for wide_string

- malduck/pe.py
Since detecting invalid PE's is pretty hard (believe me, we tried) this fix should stop those annoying FastPE error messages from popping up (see #44 for details)
Closes #44
> Handle invalid PE's in resource getter

- .github/workflows/lint-test.yml
- malduck/extractor/loaders.py
- setup.cfg
The fix for typo in pycryptodome camellia is now live and we can reenable mypy checks.
This also fixes a resulting error that appeared because types for `pkgutil.iter_modules` have been made more precise: https://github.com/python/typeshed/commit/8642d2aa97e6fbb87c06c169c72a0ebf8d1f42f1#diff-e116aacd70a29ba95251191d086f73c4b803499ebc85de2c4a775db4ff3c41b6L18
Closes #52
> Bump mypy and revert camellia type checks

- malduck/string/bin.py
- tests/test_string.py
This fixes  the following error when you bigint.pack() an integer that has an odd-length hex string, such as 1 or 1234 (0x4d2).
```
def unhex(s: Union[str, bytes]) -> bytes:
>       return binascii.unhexlify(s)
E       binascii.Error: Odd-length string
```
> Fix Bigint.pack for odd-length hex integers

- malduck/extractor/extract_manager.py
- malduck/extractor/extractor.py
- malduck/procmem/binmem.py
Raising an exception is more appropriate in Python context (and throwed isn't really a word :thinking: ).
> Replace 'throwed' with 'raised' in docstrings

- .gitignore
- malduck/compression/aplib.py
- malduck/compression/components/aplib.py
- tests/test_compression.py
Using the function malduck.aplib() returned a None object.
We can see that running the tests:
After the fixes in this PR the tests on compression are passed:
> Fix Aplib decompression

- malduck/main.py
- malduck/pe.py
This PR adds a new cli option `resources` that collects PE resources from the input files and puts them in the destination folder:
```shell
malduck
Usage: malduck [OPTIONS] COMMAND [ARGS]...
Options:
-l, --log-level TEXT         Set logging level for commands: critical,
error, warning (default), info, debug
-v, --verbose / -q, --quiet  Verbose mode (shortcut for '--log-level debug')
/ quiet mode ('--log-level error')
--version                    Show the version and exit.
--help                       Show this message and exit.
Commands:
extract    Extract static configuration from dumps
fixpe      Fix dumped PE file into the correct form
resources  Extract PE resources from an EXE into a directory
```
```shell
malduck resources MBCrackme.exe  out
Found resource 3-1 (1128 bytes)
Found …
```
> Add PE resource extraction

- malduck/extractor/extract_manager.py
> Warn user if they're trying to hurt themselves

- malduck/pe.py
- requirements.txt
- setup.py
Since patch was merged into upstream (https://github.com/erocarrera/pefile/pull/344), we can bump pefile version and remove FastPE.
Closes https://github.com/CERT-Polska/malduck/issues/79
> Bump PEFile and remove performance patch (FastPE)

- .github/workflows/lint-test.yml
- pyproject.toml
- setup.cfg
- setup.py
Python 3.6 is abandoned and is no longer available for setup in CI
> Use lint-python v2 and bump Python to 3.8

- requirements.txt
In version v4.2.3 of yara-python accessing `strings` of a `yara.Match` object returns list of tuples of the form `(<offset>,<identifier>,<data>)` as seen in [docs](https://yara.readthedocs.io/en/v4.2.3/yarapython.html#yara.Match.strings).  However, in new [v4.3.0](https://yara.readthedocs.io/en/v4.3.0/yarapython.html#yara.Match.strings) they've abstracted it to return `List[StringMatch]`, where `StringMatch` itself also has abstracted `StringMatchInstance` member.
Shouldn't be too hard to refactor, but in the meantime maybe it's best to pin
> Pin yara-python v4.2.3

- malduck/ints.py
Turns out that they are not completely free  ¯\\_(ツ)_/¯
`8.287 seconds` -> `3.863 seconds`
Should somewhat help with #90
> Remove typing cast that slowed the working of integer types

- readthedocs.yml
As per https://blog.readthedocs.com/use-build-os-config/
> Specify build os in readthedoc config file

- malduck/extractor/extract_manager.py
- malduck/procmem/binmem.py
- setup.cfg
In addition to image=False binaries, it also returns image=True versions.
In previous versions it was done by extractor, so it was working only if memory-aligned version was also "valid".
> Include image=True binaries in load_binaries_from_memory

- malduck/main.py
WIthout fixing the ImageBase the resulting PE files are not liked by Ghidra and other tools, so I think it may be useful:
[note - there seems to be some problems with files reconstructed with this method. I'm debugging this currently with @nazywam]
> Make it possible to specify a base when rebuilding the PE

- malduck/dnpe.py
- malduck/procmem/procmemelf.py
- requirements.txt
- tests/test_procmem.py
- tests/test_procmemelf.py
Bump dnfile because of breaking changes.
> Fix typing and dependencies

- malduck/disasm.py
- tests/test_disasm.py
Add support for xmmword in the dissasm class.
> Add support for xmmword ref during dissasm.

- malduck/crypto/aes.py
- malduck/crypto/winhdr.py
- malduck/procmem/binmem.py
- malduck/procmem/procmem.pyi
- malduck/yara.pyi
- readthedocs.yml
- requirements.txt
- Bumped lint-python and used newer liinter/formatter versions
- Bumped typing-extensions to use Self type and fix generic self pattern that was misunderstood by mypy in binmem
- Another version of fix for RTD (https://github.com/CERT-Polska/malduck/issues/127)
> Bump lint-python and fix RTD
